# Generated by Django 2.2 on 2020-02-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_on_post', to='wall_app.User')),
                ('users_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_commenting_on_post', to='wall_app.User')),
            ],
        ),
    ]
